language: python


python:
  - "2.7_with_system_site_packages"

install:
  - "bash ./.travis.sh"
  - "sudo apt-get install python-qt4"
  - "pip install -r requirements.txt"


before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"


script:
  - py.test
